In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 shape:', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 shape:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 shape:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)
array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 shape: (1, 3)


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3:{:3}차원' .format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


**✅ list > ndarray,   np.array(list)**

In [5]:
list2 = [1,2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
# str, int >> str타입으로 변경됨

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3,array3.dtype)

array3.astype(int)
# astype() >> ndarray내의 데이터 타입을 변경해줌

['1' '2' 'test'] <U21
[1. 2. 3.] float64


array([1, 2, 3])

**✅ array.astype(int / float / bool)**

In [6]:
array_int = np.array([1,0,3])
array_float = array_int.astype(bool)
print(array_float, array_float.dtype)

array_int1 = array_float.astype(int)
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype(int)
print(array_int2, array_int2.dtype)

[ True False  True] bool
[1 0 1] int64
[1 2 3] int64


**✅ np.arange(n)**

In [7]:
sequence_array1 = np.arange(1,11)
sequence_array2 = np.arange(11)

print(sequence_array1,sequence_array2)

print(sequence_array.dtype, sequence_array.shape)

[ 1  2  3  4  5  6  7  8  9 10] [ 0  1  2  3  4  5  6  7  8  9 10]


NameError: name 'sequence_array' is not defined

**✅ np.zeros(n), np.ones(n)**

In [ ]:
zero_array = np.zeros((2,6), dtype=int)
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((2,6), dtype=int)
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]
int64 (2, 6)
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]
int64 (2, 6)


**✅ reshape(a,b)**

In [ ]:
array1 = np.arange(10)
print('array1 : \n',array1)

array2 = array1.reshape(2,5)
print('array2 : \n',array2)

array3 = array1.reshape(5,2)
print('array3 : \n',array3)

# a * b = 10 이 되지 않는 수의 조합은 에러 발생
array_test = array1.reshape(4,3)
print('array_test : \n',array_test)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]
array2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 :\n', array2)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 :', array3)
print('array3 shape:',array3.shape)

#10개의 1row 로 된 data를 4개의 칼럼으로 나눌수는 없음 >> error
array4 = array1.reshape(-1,4)

[0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)
array3 : [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape: (5, 2)


ValueError: cannot reshape array of size 10 into shape (4)

**✅ Index: array[n]**

In [ ]:
array1 = np.arange(start=1, stop=10) # np.arange(start=1, stop=10) = np.arange(1,10)
print('array1 :', array1)

value = array1[2]
print('value : ', value)
print(type(value))

value2 = array1[-1]
print('value2 : ', value2)
print(type(value2))

array1 : [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int64'>
value2 :  9
<class 'numpy.int64'>


**✅ Index로 ndarray내의 데이터 값 수정가능**

In [ ]:
array1[3]=10
print(array1)

[ 1  2  3 10  5  6  7  8  9]


In [ ]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index가 가리키는 값: ', array2d[0,0])
print('(row=0, col=1) index가 가리키는 값: ', array2d[0,1])
print('(row=1, col=0) index가 가리키는 값: ', array2d[1,0])
print('(row=2, col=2) index가 가리키는 값: ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index가 가리키는 값:  1
(row=0, col=1) index가 가리키는 값:  2
(row=1, col=0) index가 가리키는 값:  4
(row=2, col=2) index가 가리키는 값:  9


python에서는 행(row), 열(col)을 쓰지 않음

row = axis 0

col = axis 1

1차원
axis 0

2차원
axis 0
axis 1

3차원
axis 0
axis 1
axis 2

slicing
---

In [ ]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(1,10)
array4 = array1[:3]

array5 = array1[3:]

array6 = array1[:]

print(array4)
print(array5)
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array2d = array1.reshape(3,3)
print('array2d :\n',array2d)

print('array2d[0:2, 0:2] :\n',array2d[0:2,0:2])
print('array2d[1:3, 0:3] :\n',array2d[1:3,0:3])
print('array2d[1:3, :] :\n',array2d[1:3,:])
print('array2d[:, :] :\n',array2d[:,:])

print('array2d[:2, 0] :\n',array2d[:2,0])
# [:2, 0] 👉 axis 0= :2, axis 1=0

array2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] :
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] :
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] :
 [[4 5 6]
 [7 8 9]]
array2d[:, :] :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 0] :
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[:,1])

print('array2d[0] shape:', array2d[0].shape, 'array2d[:,1]', array2d[:,1].shape)

[1 2 3]
[2 5 8]
array2d[0] shape: (3,) array2d[:,1] (3,)


1) Fancy indexing

In [9]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d : \n',array2d)

print('array2d90:2, 0:2] : \n',array2d[0:2, 0:2])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d90:2, 0:2] : 
 [[1 2]
 [4 5]]
