# 1.사이킷런의 소개와 특징

In [25]:
import sklearn
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [26]:
print(sklearn.__version__)

1.0.2


# 2.붓꽃 품종 예측하기

1️⃣ 데이터 세트 분리: 데이터를 학습 데이터와 테스트 데이터로 분리합니다. 

In [27]:
iris = load_iris()

# iris.data는 Iris data set에서 feature만으로 된 데이터를 numpy로 가지고 있다
iris_data = iris.data
iris_label = iris.target

# iris.target은 붓꽃 데이터 세트에서 레이블(결정 값)데이터를 numpy로 가지고 있다
print('iris target값:', iris_label)
print('iris taget명:', iris.target_names)

#붗꽃 data set를 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris taget명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [28]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

# First parameter : iris_data = feature data set
# Second parameter : iris_label = Lable data set
# Third parameter : test_size = scope of data set
# Fourth parameter : 호출 시 같은 학습/데이터 용 데이터 세트를 생성하기 위한 난수발생기 

2️⃣ 모델 학습: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습시킵니다.

In [29]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

3️⃣ 예측 수행: 학습된 ML 모델을 이용해 테스트 데이터의 분류(즉,붓꽃종류)를 예측합니다.

In [30]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

4️⃣ 평가 이렇게 예측된 결팟값과 테스트 데이터의 실제 결갓값을 비교해 ML 모델 성능을 평가합니다.

In [31]:
from sklearn.metrics import accuracy_score
print('예측 정확도:{0: .4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


분류, 예측 프로세스

1. 데이터 세트 분리: 데이터를 학습 데이터와 테스트 데이터로 분리합니다. 
2. 모델 학습: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습시킵니다.
3. 예측 수행: 학습된 ML 모델을 이용해 테스트 데이터의 분류(즉,붓꽃종류)를 예측합니다.
4. 평가 이렇게 예측된 결팟값과 테스트 데이터의 실제 결갓값을 비교해 ML 모델 성능을 평가합니다.

# 3.사이킷런의 기반 프레임워크 익히기

## Estimator 이해 및 fit(), predict() 메서드

fit( ): 모델 학습을 위한 메서드

predict( ): 학습된 모델의 예측을 위한 메서드

Classifier: 분류 알고리즘을 구현한 클래스

Regressor: 회귀 알고리즘을 구현한 클래스

위 두가지를 합쳐서 Estimator 클래스라고 부름 = *지도학습*의 모든 알고리즘을 구현한 클래스

Classifier
1️⃣Decision Tree Classfier
2️⃣RandomForesrClassifier
3️⃣GaussianNB
4️⃣SVC

Regrression 
1️⃣LinearRegression
2️⃣Ridge
3️⃣Lasso
4️⃣RandomForestRegressor 
5️⃣GradientBoostingRegressor

## 사이킷런의 주요 모듈

https://www.notion.so/bf64178bd85e42a3b2a85493396bceb8

## 내장된 예제 데이터 세트


https://www.notion.so/b5ed10a250c34af39e59096f58a59dcd

In [32]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [33]:
keys = iris_data.keys()
print('Keys of iris dataset:',keys)

Keys of iris dataset: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [34]:
print('\n type of feature_names :', type(iris_data.feature_names))
print('shape of feature_names', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n type of target_names', type(iris_data.target_names))
print('shape of target_names', len(iris_data.target_names))
print(iris_data.target_names)

print('\n type of data :', type(iris_data.data))
print('shape of data :', iris_data.target.shape)
print(iris_data['data'])

print('\n data of target :', type(iris_data.target))
print('shape of target :', iris_data.target.shape)
print(iris_data.target)


 type of feature_names : <class 'list'>
shape of feature_names 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 type of target_names <class 'numpy.ndarray'>
shape of target_names 3
['setosa' 'versicolor' 'virginica']

 type of data : <class 'numpy.ndarray'>
shape of data : (150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0

# 4.Model Selection 모듈 소개


__model Selection module__ : 학습 데이터, 테스트 데이터를 분리, 교차 검증 분할 및 평가 / Estimatior의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스 제공

## 학습/테스트 데이터 세트 분리 - train_test_split( )

In [35]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)


# 학습 데이터 세트로 예측 수행
pred = dt_clf.predict(train_data)
print('accuracy score:',accuracy_score(train_label,pred))


accuracy score: 1.0


In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

# 데이터 븐류( 학습 70%, 검정 30% )
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

# train data 학습
dt_clf.fit(X_train, y_train)

# test 데이터로 정확도 예측
pred = dt_clf.predict(X_test)
accuracy_score1 = accuracy_score(y_test, pred)

print('accuracy score: {0:.4f}'.format(accuracy_score(y_test,pred)) )

accuracy score: 0.9556


## 교차 검증

### K 폴드 교차 검증

https://www.notion.so/0783d3c758b946cbba493023c47133f6

In [37]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성.
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붗꽃 데이터 세트 크기:', features.shape[0])

붗꽃 데이터 세트 크기: 150


In [38]:
n_iter = 0

# KFold 객체 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
    # kfold.split() 으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    # 학습 및 예측
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1
    
    # 반복 시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print('\n#{0} 교차검증 정확도: {1}, 학습데이터 크기: {2}, 검증데이터 크게: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)

    
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차검증 정확도: 1.0, 학습데이터 크기: 120, 검증데이터 크게: 30
#1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차검증 정확도: 0.9667, 학습데이터 크기: 120, 검증데이터 크게: 30
#2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차검증 정확도: 0.8667, 학습데이터 크기: 120, 검증데이터 크게: 30
#3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차검증 정확도: 0.9333, 학습데이터 크기: 120, 검증데이터 크게: 30
#4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차검증 정확도: 0.7333, 학습데이터 크기: 120, 검증데이터 크게: 30
#5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


### Stratified K 폴드

In [39]:
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [40]:
kfold = KFold(n_splits = 3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('\n\n## 교차 검증: {0} ##'.format(n_iter))
    
    print('label_train data distribution:\n', label_train.value_counts())
    print('\nlabel_test data distribution:\n', label_test.value_counts())



## 교차 검증: 1 ##
label_train data distribution:
 1    50
2    50
Name: label, dtype: int64

label_test data distribution:
 0    50
Name: label, dtype: int64


## 교차 검증: 2 ##
label_train data distribution:
 0    50
2    50
Name: label, dtype: int64

label_test data distribution:
 1    50
Name: label, dtype: int64


## 교차 검증: 3 ##
label_train data distribution:
 0    50
1    50
Name: label, dtype: int64

label_test data distribution:
 2    50
Name: label, dtype: int64


In [41]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('label_train data distribution:\n', label_train.value_counts())
    print('label_test data distribution:\n', label_test.value_counts(),'\n\n')

## 교차 검증: 1
label_train data distribution:
 2    34
0    33
1    33
Name: label, dtype: int64
label_test data distribution:
 0    17
1    17
2    16
Name: label, dtype: int64 


## 교차 검증: 2
label_train data distribution:
 1    34
0    33
2    33
Name: label, dtype: int64
label_test data distribution:
 0    17
2    17
1    16
Name: label, dtype: int64 


## 교차 검증: 3
label_train data distribution:
 0    34
1    33
2    33
Name: label, dtype: int64
label_test data distribution:
 1    17
2    17
0    16
Name: label, dtype: int64 




In [42]:
n_iter = 0

# StraitifiedKFold의 split( ) 호출시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_size in skfold.split(features, label):
    
    # split( )으로 반환된 인덱스를 이용해 학습용, 겁증용 테스트 데이터 추출
    x_train, x_test = features[train_index], features[test_size]
    y_train, y_test = label[train_index], label[test_size]
    
    # 학습 및 예측
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    
    # 정확도
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred))
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print('교차 검증 {0}\n 학습데이터 크기: {1}\n 검증데이터 크기: {2}\n 정확도: {3}\n'.format(n_iter, train_size, test_size, accuracy))
    
    cv_accuracy.append(accuracy)


교차 검증 1
 학습데이터 크기: 100
 검증데이터 크기: 50
 정확도: 1.0

교차 검증 2
 학습데이터 크기: 100
 검증데이터 크기: 50
 정확도: 1.0

교차 검증 3
 학습데이터 크기: 100
 검증데이터 크기: 50
 정확도: 1.0



### 교차 검증을 보다 간편하게 - cross_val_score()

## GridSearchCV-교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에

# 5.데이터 전처리

## 데이터 인코딩

### 레이블 인코딩

### 원-핫 인코딩(One-Hot Encoding)

## 피처 스케일링과 정규화

## StandardScaler

## MinmaxScaler

## 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점

# 사이킷런으로 수행하는 타이타닉 생존자 예측